services:

  backend:
    build: ./backend
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports:
      - "3000:3000" # "3000:80" for static adapter when serving with httpd
    depends_on:
      - backend
